# Generated by Django 4.2.18 on 2025-01-31 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('short_alias', models.CharField(editable=False, max_length=6, unique=True)),
                ('long_url', models.URLField(default='', help_text='Paste in the full URL starting with HTTP or HTTPS.', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.PositiveIntegerField(default=0, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['short_alias'], name='shortener_s_short_a_581efd_idx'), models.Index(fields=['-created_at'], name='shortener_s_created_96ea04_idx'), models.Index(fields=['-clicks'], name='shortener_s_clicks_317034_idx')],
            },
        ),
    ]
