# Generated by Django 4.2.18 on 2025-01-25 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('short_alias', models.CharField(editable=False, max_length=6, unique=True)),
                ('long_url', models.URLField(default='', help_text='Paste in the full URL starting with HTTP or HTTPS.', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.PositiveIntegerField(default=0, editable=False)),
                ('og_site_name', models.CharField(blank=True, max_length=64, null=True)),
                ('og_type', models.CharField(blank=True, max_length=64, null=True)),
                ('og_title', models.CharField(blank=True, max_length=64, null=True)),
                ('og_description', models.CharField(blank=True, max_length=500, null=True)),
                ('og_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('og_image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('tw_site', models.CharField(blank=True, max_length=64, null=True)),
                ('tw_title', models.CharField(blank=True, max_length=64, null=True)),
                ('tw_description', models.CharField(blank=True, max_length=500, null=True)),
                ('tw_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('tw_image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('tw_image_alt', models.CharField(blank=True, max_length=500, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
