# Generated by Django 4.2.18 on 2025-02-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='long_url',
            field=models.URLField(default='', help_text='Place the full URL starting with https://', max_length=2048),
        ),
    ]
