# Generated by Django 4.2.18 on 2025-01-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='long_url_sha256',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='long_url',
            field=models.URLField(default='', help_text='Paste in the full URL starting with HTTP or HTTPS.'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_alias',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
