# Generated by Django 4.2.18 on 2025-01-26 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='og_image_url',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='og_site_name',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='og_type',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='og_url',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='tw_description',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='tw_image_alt',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='tw_image_url',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='tw_site',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='tw_title',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='tw_url',
        ),
    ]
