# Generated by Django 4.2.17 on 2025-01-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_rename_url_shorturl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='click_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_alias',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
