# Generated by Django 4.2.18 on 2025-01-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_shorturl_long_url_sha256_shorturl_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
