# Generated by Django 4.2.18 on 2025-01-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_shorturl_long_url_alter_shorturl_og_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
